# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request] # Trigger the workflow on push or pull request events

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2 # Use the latest version of setup-java action
        with:
          java-version: '8' # Use single quotes for strings
          distribution: 'adopt' # Use AdoptOpenJDK distribution 
      - name: Check current Directory and info (temporal)
        run: ls -R /home/runner/work/
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run Java Application
        run: java -jar target/bing-wallpaper-jar-with-dependencies.jar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2 # Use the latest version of upload-artifact action
        with:
          name: artifact
          path: picture/*
